FROM arm64v8/debian

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install chromium-driver -y

RUN apt-get install g++ -y
RUN apt-get install make -y
RUN apt-get install binutils -y
RUN apt-get install cmake -y
RUN apt-get install libboost-system-dev -y
RUN apt-get install libssl-dev -y
RUN apt-get install zlib1g-dev -y
RUN apt-get install libcurl4-openssl-dev -y
RUN apt-get install cmake git -y

RUN apt-get install pkg-config -y
RUN apt-get install libjsoncpp-dev -y
